### ISSUE TITLE
Bug in assert_hook with streams.

### ISSUE THREAD

**Issue by bradleyayers** [dag/attest#130]
Example: (**Edit: corrected the example, thanks Simon**)

```
from attest import assert_hook, Tests
from io import StringIO

tests = Tests()

@tests.test
def stringio():
    stream = StringIO(u'hi')
    assert stream.read() == u'hi'
```

However it works if the `.read()` isn't done in the `assert` line:    from attest import assert_hook, Tests

```
from io import StringIO

tests = Tests()

@tests.test
def stringio():
    content = StringIO(u'hi').read()
    assert content == u'hi'  # works
```

**Comment by SimonSapin** [comment]
Hi,

Thanks for the report. This is a known bug/behavior: each assert expression is evaluated once to see if the test passes, and in case of failure the fancy reporter evaluates it once more (though partially) to build its output.

I have not tested your examples, but I expect they would both work. In the first one the reporter would create a new StringIO and have the expected behavior. By the way what exactly do you call "not working"? What behavior/output do you get?

Here is a third example that I expect does **not** work and guess is what you meant:

```
from attest import assert_hook, Tests
from io import StringIO

tests = Tests()

@tests.test
def stringio():
    file_like = StringIO(u'hi')
    assert file_like.read() == u'hi'
```

In this case both evaluations have the same StringIO object, and the second call to read() gives the empty string since the internal pointer is already at the end of the file. The same bugs can be observed with generators that can be "consumed" only once.

This might not be easy to fix but I’ll investigate.

In the meantime remember that the assert expression is evaluated twice on failed asserts, though this only affects reporting.

**Comment by bradleyayers** [comment]
Oops! You're absolutely right (I've fixed it in my original post). In what I was doing, it seemed like the assert statement was being evaluated twice _even_ when the assert **succeeded**. This meant that a test that would normally work fine, would have an `AssertionError` raised. It seems like Attest evaluates the expressions upfront to build the error message "just in case", and then performs the comparison, at which time since the stream has been exhausted, it fails.

**Comment by SimonSapin** [comment]
Which version are you using? I think this (evaluating twice on success) was fixed in git since the latest release.

(Yes, the next release is long overdue ...)

**Comment by bradleyayers** [comment]
I'm using the latest stable :P -- 0.5.2

**Comment by SimonSapin** [comment]
Do you still have the bug with the git version? Install it with `pip install git+git://github.com/dag/attest.git`.

It’s fairly stable, we just have not written the documentation for changes since 0.5.2 yet.

**Comment by bradleyayers** [comment]
I've done a little more research. Given the file:

```
from attest import assert_hook, Tests
from io import StringIO


tests = Tests()


@tests.test
def stringio():
    stream = StringIO(u'hi')
    assert stream.read() == u'hi'


if __name__ == '__main__':
    tests.run()
```

If I save it to `sample.py` and execute it via `python sample.py`, it works. However if I add a `setup.py` with the lines:

```
#!/usr/bin/env python
from setuptools import setup

setup(
    ...
    tests_require=['Attest >=0.4'],
    test_loader='attest:FancyReporter.test_loader',
    test_suite='sample.tests',
    ...
)
```

And then run `python setup.py test`, it fails. If I remove the `assert_hook` import, it works again. Changing `FancyReporter` to any other reporter makes no difference.

Upgrading to the latest Git version fixes the issue.

**Comment by SimonSapin** [comment]
“It works” when run directly because the assert hook does not work in that case. The assert hook is implemented with a import hook that rewrites assert statements. That import hook is itself installed when Attest is first imported, which in your first test case happens after your script was imported.

**Comment by bradleyayers** [comment]
Ahh, I see! Well that's all nice and consistent then. Thanks for the follow up.
