### ISSUE TITLE
Integration with Flask+nose

### ISSUE THREAD

**Issue by danjac** [dag/attest#33]
I'm planning to integrate attest with Flask-Testing. The idea is to have a TestBase subclass that handles all the Flask context setup etc, which users can then subclass.

You can see the code in the attest-integration branch here:

http://bitbucket.org/danjac/flask-testing/src/36689759f56c

The issue is with the actual tests used with Flask-Testing itself. I'd like to maintain both unittest and attest options, as many users will prefer to use the standard (and for backward compatibility). However this involves running everything under nosetests as part of the standard test suite. Nose tries to run the attest TestBase as a unittest.TestCase, and can't handle the @test decorator (you can see the test code).

Please could you let me know if a) I'm doing something wrong or b) nose can't be used along with attest. If not, I might look at other options such as a separate Flask-Attest extension.

I'd also be grateful for a review of the code used to see that it's following best practices for attest.

Thanks.

**Comment by danjac** [comment]
On reflection, I've decided to create a new extension, Flask-Attest:

http://bitbucket.org/danjac/flask-attest

Your feedback would be much appreciated !

**Comment by dag** [comment]
I've been meaning to make a Flask-Attest extension; I'll have a look at yours.

**Comment by dag** [comment]
To be frank, it's nose's fault that attest doesn't work with it: this is one of the reasons for attest. This is the sort of problems you run into with a global collection of implicit tests. As a workaround, I could make `@test` set `_test` instead of `__test__` so at least nose wont pick those up, and to make it work with nose maybe you could do something with `Tests.test_suite` which creates a `unittest.TestSuite` from an attest collection.

Your Flask-Attest seem a little different from how I use Attest with Flask, actually I don't know if it even warrants an extension because it's so simple but it might still be handy and it could provide a Flask-Script `Command` for running the tests etc.

If I can get Attest to work better with Nose perhaps you could merge your Flask-Attest in Flask-Testing and I/we can make a Flask-Attest more in the spirit of Attest?

In my own app this is what I currently have:

```
def flask_tests():
    tests = Tests()

    @tests.context
    def request_context():
        app = create_app('stutuz.configs.testing')
        with app.test_request_context():
            app.preprocess_request()
            yield Assert(app.test_client())
            app.process_response(app.response_class())

    return tests
```

This could be generalized to take the `create_app` factory and an existing `Tests` instance so it can be combined with similar functions, i.e.

```
suite = flask_request(db_connection(Tests()))
```

The inner `Tests()` could of course be optional, I'm also considering a more readable syntax that would require a change in Attest:

```
suite = Tests(contexts=[flask_request, db_connection])
```

The `yield Assert(app.test_client())` means we can write tests like this:

```
@suite.test
def api(client):
    client.get('/api').mimetype == 'application/json'
```

I also envision a function for asserting against many attributes at once for responses,

```
def assert_response(response, status=200, mimetype='text/html', data=None...)
```

So that it asserts overridable defaults, the `data` asserts `in` not `==`, the `status` can also take an iterable, etc. Then "redirects" is a simple matter of,

```
assert_response(response, status=(301, 302), location=expected)
```

which could easily be made an `assert_redirects` helper.

I'm not sure yet if I think `assert_x` functions is the right idiom though.

Some other points:
- I like context managers more than setup+teardown
- I prefer functional style (especially for Flask) over TestBase
- I don't use Twill, don't really see its value, and hate the warnings it throws :D

**Comment by danjac** [comment]
I agree with you on Twill :-) It was there by request from Flask-Testing's early days, and TBH I'd be happy to drop it as I don't use it myself.

On other matters:

I still think it would be better to have Flask-Attest as a separate extension, for a number of reasons:

1) people are unlikely to mix unittest with attest - they'll use one or the other. I'd rather have a small Flask-Attest extension with a clean codebase.

2) I like attest the way it is :-) In other words, it's nicely non-magical, and if mixing it with nosetests makes it less so, then don't do it. Getting nosetests working with attest+unittest in the same test suite wasn't working, so I broke it into another extension.

3) I agree with you on preferring the context manager way of doing things, however it would be nice to support both functional and object idioms as attest does this. Much of the code can be broken out into a context manager.

4) It would be nice to have helpers such as assert_response available.

**Comment by danjac** [comment]
Having had the chance to play with attest a bit more, I'm inclined to agree that it's simple enough to use without an extension.

However I'm not sure it's worth adding anything to Flask-Testing (which is specifically built around unittests). A Flask-Attest extension would still be nice, but might just consist of some friendly helper functions. 

Anyway, it's a joy rewriting tests to use attest rather than unittest. Definitely much nicer !

**Comment by dag** [comment]
Thanks :)

I agree TestBase should be supported in a potential extension. The right way to add multiple contexts to TestBase might be super:

```
class API(FlaskRequest):
    def __context__(self):
        with FlaskRequest.__context__(self):
            do_more_stuff()
```

This'd be very idiomatic for Python and also arguably a little clunky. Shrug. I _could_ add a `@context` decorator that allows multiple contexts just like in functional style. I think it makes less sense for classes than with functions though. Thoughts?

**Comment by dag** [comment]
I guess what I'm thinking is that "the obvious way to do it" (Zen!) with classes is multiple-inheritance and super.
