### ISSUE TITLE
Share contexts between collections

### ISSUE THREAD

**Issue by danjac** [dag/attest#34]
Is there a way for collections in a test to share contexts ?

Currently appears that each collection in a Tests instance has its own context. This is difficult if for example you want to share some contexts between collections (for example, creating/destroying a database) while keeping others isolated (for example, injecting a fixture for a specific suite of tests, which you don't want in other tests).

It should be possible to share contexts in such a way between collections, perhaps through having a separate list of "global" contexts that apply to all collections in a Tests instance.

**Comment by dag** [comment]
I use a factory function to add a context to a collection, and then init my collection with that function instead of the Tests class.

```
suite = flask_tests()
```

I don't like the idea of a global collection because that means the smaller suites depend on the bigger suite to run. Might not matter a lot in practice (is it valuable to run smaller collections alone?) but feels wrong in theory, design-wise.

So, similar to how in Flask we have init_app methods that set before and after request callbacks, we achieve extensibility and reusability with "context injectors":

```
def inject_context(tests=None):
    if tests is None:
        tests = Tests()
    @tests.context
    def reusable():
        yield stuff
    return tests
```

This can be used in many ways:

```
suite = inject_context()
suite = inject_context(other_context())
suite = Tests()
inject_context(suite)
```

etc. Thoughts?

**Comment by danjac** [comment]
Makes a lot more sense, and follows good practice in writing tests.
